name: JCore
main: com.jourd1.jgames.jcore.JCore
description: desc
version: ${project.version}
api-version: 1.21.4
commands:
  heal:
    description: Heal player
    usage: /heal [player]
  specmenu:
    description: Ouvre le menu de spectateur
    usage: /specmenu