name: JBedWars
main: com.jourd1.jgames.jbedwars.JBedWars
description: desc
version: ${project.version}
depend: [JCore]
api-version: 1.21.4
commands:
  menu:
    description: Ouvre le menu personnalisé
    usage: /menu